# Generated by Django 2.0.6 on 2018-07-22 16:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckinInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(default='', max_length=20, verbose_name='用户id')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('department', models.CharField(max_length=20, verbose_name='部门')),
                ('position', models.CharField(max_length=20, verbose_name='职务')),
                ('checkin_time', models.DateTimeField(auto_now_add=True, verbose_name='签到时间')),
            ],
            options={
                'verbose_name': '签到信息',
                'verbose_name_plural': '签到信息',
                'ordering': ['-checkin_time'],
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='会议名称')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='二维码')),
                ('state', models.BooleanField(default=True, verbose_name='会议状态')),
                ('meeting_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='开会时间')),
            ],
            options={
                'verbose_name': '会议信息',
                'verbose_name_plural': '会议信息',
            },
        ),
        migrations.AddField(
            model_name='checkininfo',
            name='meeting_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkin.Meeting', verbose_name='会议'),
        ),
    ]
